name: Autobump

on:
  schedule:
    - cron: '30 2 * * 1-5'
  workflow_dispatch: {} # allow manual trigger

jobs:
  autobump-go:
    name: Go
    runs-on: ubuntu-latest
    steps:

    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.1

    - name: Configure Git user
      run: |
        git config --global user.email "ocf-qe@redhat.com"
        git config --global user.name "Serverless QE"

    - uses: actions/checkout@v4

    - name: Autobump
      run:
        .github/workflows/autobump.sh
        --repo ${{ github.repository }}
        --branch autobump/go
        --dep github.com/openshift-knative/hack
      env:
        GH_TOKEN: ${{ secrets.SERVERLESS_QE_ROBOT }}
